Stylaaa.Admin/Controllers/PaymentMethodController.cs
using Microsoft.AspNet.Identity;
using Stylaaa.Core.Helper;
using Stylaaa.Core.Models;
using Stylaaa.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stylaaa.Admin.Controllers
{
    public class PaymentMethodController : BaseController
    {
        private PaymentMethodServices _service;
        private UserService _user;
        public PaymentMethodController()
        {
            _service = new PaymentMethodServices();
            _user = new UserService();
        }
        public ActionResult Index()
        {
            string UserId = User.Identity.GetUserId();
            IQueryable<PaymentMethodModel> PaymentmethodList = _service.IQueryable_GetAllPaymentMethods(_user.GetLanguage(UserId));
            return View(PaymentmethodList);
        }

        public ActionResult AddPaymentMethod()
        {
            AdminPaymentMethodModel model = new AdminPaymentMethodModel();
            List<PaymentMethodLanguageModel> PaymentLanguage = new List<PaymentMethodLanguageModel>();
            PaymentLanguage.Add(new PaymentMethodLanguageModel()
            {
                LanguageId = languageType.English,
                LanguageName = languageType.English.ToString(),
            });

            PaymentLanguage.Add(new PaymentMethodLanguageModel()
            {
                LanguageId = languageType.German,
                LanguageName = languageType.German.ToString(),
            });

            model.PaymentMethodLanguageList = PaymentLanguage;           
            ViewBag.Action = "AddPaymentMethod";
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> InsertOrUpdatePayment(AdminPaymentMethodModel model)
        {
            if (ModelState.IsValid)
            {
                bool isDuplicate = _service.IsPaymentMethodDuplicate(model);
                if (isDuplicate)
                {
                    OnBindMessage(AlertStatus.danger, "Duplicate Category Name");
                    ModelState.AddModelError("", "Duplicate Category Name");
                }
                else
                {
                    ResponseModel<object> mResult = new ResponseModel<object>();
                    mResult = await _service.InsertOrUpdatePayment(model);
                    OnBindMessage(mResult.Status, mResult.Message);

                    if (mResult.Status == ResponseStatus.Success)
                        return RedirectToActionPermanent("Index");
                }
            }
            return View("AddPaymentMethod", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            AdminPaymentMethodModel model = await _service.GetPaymentmethodDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            return View("AddPaymentMethod", model);
        }

        //[HttpPost]
        //public async Task<ActionResult> Edit(PaymentMethodModel model)
        //{
        //    ResponseModel<object> mResult = new ResponseModel<object>();
        //    if (ModelState.IsValid)
        //    {
        //        mResult = await _service.AddPaymentMethod(model);
        //        if (mResult.Status == ResponseStatus.Success)
        //        {
        //            TempData["alertModel"] = new AlertModel(AlertStatus.success, "Payment Method Edited successfully !");
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            string Msg = (!String.IsNullOrWhiteSpace(mResult.Message) ? mResult.Message : "Failed to Edit Payment Method!");
        //            TempData["alertModel"] = new AlertModel(AlertStatus.danger, Msg);
        //            ModelState.AddModelError("", Msg);
        //        }
        //    }
        //    ViewBag.Action = "Edit";
        //    return View("AddPaymentMethod", model);
        //}

        public async Task<ActionResult> Delete(long Id)
        {
            ResponseModel<object> mResult = await _service.DeleteMethodById(Id);
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            return RedirectToAction("Index");
        }
    }
}

Stylaaa.Admin/Views/PaymentMethod/AddPaymentMethod.cshtml
@model AdminPaymentMethodModel
@{
    ViewBag.Title = "Add Payment Method";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string action = ViewBag.Action;
}

@Styles.Render("~/css/wizard")

<section id="validation">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">@action Payment Method</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        @using (Html.BeginForm("InsertOrUpdatePayment", "PaymentMethod", FormMethod.Post, new { @id = "submitForm", @class = "steps-validation wizard-circle"}))
                        {
                            if (Model != null && Model.Id > 0)
                            {
                                @Html.HiddenFor(x => x.Id)
                            }                           
                                                        
                            for (int i = 0; i < Model.PaymentMethodLanguageList.Count; i++)
                            {
                                @Html.HiddenFor(x => x.PaymentMethodLanguageList[i].LanguageId)
                                <h6>@Model.PaymentMethodLanguageList[i].LanguageName</h6>

                                <fieldset>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>
                                                     Name  <span class="red">*</span>
                                                </label>
                                                @Html.TextBoxFor(x => x.PaymentMethodLanguageList[i].PaymentMethodName, new { @class = "form-control required" })
                                                @Html.ValidationMessageFor(x => x.PaymentMethodLanguageList[i].PaymentMethodName)
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>
                                                    Text  <span class="red">*</span>
                                                </label>
                                                @Html.TextBoxFor(x => x.PaymentMethodLanguageList[i].PaymentMethodText, new { @class = "form-control required" })
                                                @Html.ValidationMessageFor(x => x.PaymentMethodLanguageList[i].PaymentMethodText)
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    <script src="@Url.Content("~/Content/Jquery/GeneralScript.js")"></script>
    @Scripts.Render("~/jQuery/stepWizard")
    <script type="text/javascript">
        ActiveMenu("AddPaymentMethod");
    </script>
}

Stylaaa.Admin/Views/PaymentMethod/Index.cshtml
@model IQueryable<PaymentMethodModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@using (Html.BeginForm("Delete", "PaymentMethod", FormMethod.Post, new { @class = "form-horizontal form-simple", @id = "frmDelete" }))
{
    @Html.Hidden("Id")
}

@helper ActionButtons(long Id)
{
    <div class="form-group row">
        <a href="@Url.Action("Edit", "PaymentMethod",new { @Id=Id })" class="btn btn-sm btn-primary btn-blue">
            <i class="icon-edit2"></i> Edit
        </a>
        <a href="javascript:;" class="btn btn-sm btn-danger btnDelete" data-id="@Id">
            <i class="icon-trash4"></i> Delete
        </a>
    </div>
}


<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Payment Methods</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li>
                                <a href="@Url.Action("AddPaymentMethod","PaymentMethod")">
                                    <i class="icon-plus3"></i>  Add New
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {

                               column.Add(p => p.PaymentMethod)
                               .Titled("Payment Method")
                               .Sortable(true)
                               .Filterable(true);

                               column.Add(p => p.PaymentMethodText)
                               .Titled("Payment Method Text")
                               .Sortable(true)
                               .Filterable(true);                                                              

                               column.Add()
                               .Titled("Action")
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => ActionButtons(x.PaymentMethodId));

                           }).Selectable(false).WithPaging(30)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.min.js")"></script>
    <script type="text/javascript">
        ActiveMenu("PaymentMethod");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');

        $('.btnDelete').on('click', function () {
            $('#frmDelete #Id').val($(this).data('id'));
            swal({
                title: "Are you sure?",
                //text: "You will not be able to recover this payment method and related data",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DA4453",
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel.",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    swal("Delete!", "Selected payment method will be deleted, and will not be rollback!!", "success");
                    $('#frmDelete').submit();
                    return true;
                } else {
                    swal("Cancelled", "It's safe.", "error");
                }
            });
        });
    </script>
}