Stylaaa.Admin/Controllers/PostController.cs
using Stylaaa.Core.Helper;
using Stylaaa.Core.Models;
using Stylaaa.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stylaaa.Admin.Controllers
{
    public class PostController : BaseController
    {
        private PostServices _service;

        public PostController()
        {
            _service = new PostServices();
        }

        // GET: Post
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AllPost()
        {
            IQueryable<getAllPostlist> GetAllPost = _service.GetPostListForAdmin();
            return View(GetAllPost);
        }

        public async Task<JsonResult> DeletePostByAdmin(long Id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();

            mResult = await _service.DeletePost(Id);
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            if (mResult.Status == ResponseStatus.Success)
                return Json(mResult, JsonRequestBehavior.AllowGet);
            //if (mResult.Result)
            //    return RedirectToAction("AllStylish");
            //else
            //    return RedirectToAction("AllUsers");
            else
                return Json(mResult, JsonRequestBehavior.AllowGet);
           
        }

        public async Task<ActionResult> Postdetail(long Id)
        {
            PostDetailModel model = await _service.PostDetailById(Id);
            return View(model);
        }

        public ActionResult ReportedPost()
        {
            IQueryable<ReportedPostList> reportedPost = _service.GetReportedPostlist();
            return View(reportedPost);
        }

        public async Task<ActionResult> DeleteRepoetedPost(long Id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();

            mResult = await _service.DeletePost(Id);
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            return RedirectToAction("ReportedPost");
        }

        public ActionResult SpamComments()
        {
            IQueryable<SpamCommentsListModel> model = _service.GetSpamComments();
            return View(model);               
        }

        public async Task<ActionResult> DeleteSpamComments(long Id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            mResult = await _service.DeleteSpamComment(Id);
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            return RedirectToAction("SpamComments");
        }

    }
}

Stylaaa.Admin/Controllers/UserController.cs
using Stylaaa.Core.Helper;
using Stylaaa.Core.Models;
using Stylaaa.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stylaaa.Admin.Controllers
{
    public class UserController : BaseController
    {
        private CoreUserServices _Users;
        private StylishServices _stylish;
        private UserService _service;


        public UserController()
        {
            _Users = new CoreUserServices();
            _stylish = new StylishServices();
            _service = new UserService();
        }
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AllUsers()
        { 
            IQueryable<UserDetailModel> objUsers = _Users.getAllUsers_IQueryable();
            ViewBag.active = "Users";
            return View(objUsers);
        }

        public ActionResult AllStylish()
        {
            IQueryable<UserDetailModel> objStylish = _stylish.GetAllStylishDetail();
            ViewBag.active = "Stylist";
            return View("AllUsers", objStylish);
        }

        [HttpPost]
        public async Task<JsonResult> ActiveToggle(string Id)
        {
            ResponseModel<bool> mResult = await _service.ActiveToggle(Id);
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Detail(string id)
        {
            Role role = _service.GetRoleById(id);
            if (role == Role.User)
            {
                ViewUserDetail objUser = await _Users.GetUserDetail(id);
                if (objUser == null)
                    return RedirectToAction("AllUsers");
                else
                    return View("UserDetail", objUser);
            }
            else
            {
                ViewStylishDetailsModel objStylish = await _stylish.GetStylishDetail(id);
                if (objStylish == null)
                    return RedirectToAction("AllStylish");
                else
                    return View(objStylish);
            }
        }

        public async Task<JsonResult> DeleteUser(string id)
        {
            ResponseModel<bool> mResult = new ResponseModel<bool>();
            mResult = await _service.DeleteUser(id);
            if (mResult.Status == ResponseStatus.Success)
                return Json(mResult, JsonRequestBehavior.AllowGet);
            //if (mResult.Result)
            //    return RedirectToAction("AllStylish");
            //else
            //    return RedirectToAction("AllUsers");
            else
                return Json(mResult, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("AllUsers");

        }
        
        public async Task<ActionResult> RemoveAll(string SelectedUserId)
        {
            if (SelectedUserId != null)
            {
                List<string> UsersId = SelectedUserId != null ? SelectedUserId.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).ToList() : null;
                foreach (var item in UsersId)
                {
                    ResponseModel<bool> mResult = await _service.DeleteUser(item);
                }
                TempData["alertModel"] = new AlertModel(AlertStatus.success, string.Format("{0} Users delete successfully", UsersId.Count()));
            }
            else
                TempData["alertModel"] = new AlertModel(AlertStatus.success, "please select User");
            return RedirectToAction("AllStylish");
        }
    }
}

Stylaaa.Admin/Views/Post/AllPost.cshtml
@model IQueryable<getAllPostlist>
@using GridMvc.Html
@{
    ViewBag.Title = "AllPost";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@Styles.Render("~/css/gridMvc")
@helper LoadImage(getAllPostlist item)
{
    if (item.PostPic != null)
    {
            <img src="@(GlobalConfig.PostImageUrl + item.PostPic )" @*alt="@item.Name"*@ height="100" width="100" />
}
else
{
        <img src="~/Files/DefaultImages/video.png" @*alt="@item.Name"*@ height="100" width="100" />
}
}

@helper ActionButtons(long PostId)
{
    <a href="javascript:;" class="btn btn-sm btn-danger btnDelete" data-id="@PostId">
        <i class="icon-trash4"></i> Delete
    </a>
    @*<a href="@Url.Action("DeletePostByAdmin", "Post", new { @Id = PostId })" class="btn btn-sm btn-danger btnDelete" data-id="@PostId">
            <i class="icon-trash4"></i> Delete
        </a>*@

    <a href="@Url.Action("Postdetail", "Post", new { @Id = PostId })" class="btn btn-sm btn-primary btn-blue">
        <i class="icon-box"></i> Detail
    </a>
}


@helper HashTags(List<PostHashTaglistModel> tagList)
{
    <ul>
        @foreach (var tag in tagList)
        {
            <li>@tag.hashtag</li>
        }
    </ul>
}

@helper LoadPostBy(getAllPostlist item)
{
    <a href="@Url.Action("Detail", "User", new { @id = item.StylishId})">@item.Name</a>
}

<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Post </h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add()
                              .Titled("File")
                              .Sanitized(false).Encoded(false)
                              .RenderValueAs(x => LoadImage(x));

                               column.Add(p => p.Name)
                               .Titled("Name")
                               .Sortable(true)
                               .Filterable(true)
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => LoadPostBy(x));

                               column.Add(p => p.HasTag)
                              .Titled("Hashtag")
                              .Sortable(true)
                              .Filterable(true)
                              .Sanitized(false).Encoded(false)
                              .RenderValueAs(x => HashTags(x.HasTag));

                               column.Add(p => p.CreatedDate)
                             .Titled("Created Date")
                             .Sortable(true)
                             .Filterable(true)
                             .RenderValueAs(p => p.CreatedDate.ToString("dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture));

                               column.Add()
                               .Titled("Action")
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => ActionButtons(x.PostId));

                           }).Selectable(false).WithPaging(30)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    @Scripts.Render("~/jQuery/validate")
    <script src="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.min.js")"></script>
    <script type="text/javascript">
        ActiveMenu("Post");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');

        $(function () {
            $('.btnDelete').on('click', function () {
                var control = $(this);
                var Url = '@Url.Action("DeletePostByAdmin", "Post")';
                //$('#frmDelete #id').val($(this).data('id'));
                swal({
                    title: "Are you sure?",
                    //text: "You will not be able to recover user related data",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DA4453",
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel.",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function (isConfirm) {
                    if (isConfirm) {
                        $.post(Url, { 'id': $(control).attr('data-id') }, function (response) {
                            if (response.Status == 1) {
                                setTimeout(function () {
                                    //control.parent().find(".activate").show()
                                    control.parent().parent().hide();
                                }, 300);
                                swal("Deleted!", response.Message, "success");

                            }
                            else {
                                control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-trash-o');
                                swal("Error", response.Message, "error");
                            }
                        });
                    } else {
                        control.children('i').removeClass('icon-spinner10 spinner').addClass('icon-trash-o');
                        swal("Cancelled", "Your record is safe :)", "info");
                    }
                    //if (isConfirm) {
                    //    swal("Delete!", "Selected User will be deleted, and will not be rollback!!", "success");
                    //    $('#frmDelete').submit();
                    //    return true;
                    //} else {
                    //    swal("Cancelled", "It's safe.", "error");
                    //}
                });
            });
        });

    </script>


}

Stylaaa.Admin/Views/Post/Postdetail.cshtml
@model PostDetailModel
@{
    ViewBag.Title = "Postdetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int j = 0;
}

<section id="validation">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Post By : @Model.Name</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        <div class="form-group row">
                            <div class="col-md-7">
                                <div class="form-group row">
                                    <div class="col-md-10">
                                        @if (!string.IsNullOrEmpty(Model.ProfileImageNAme))
                                        {
                                            <img src="@(GlobalConfig.UserImageUrl+Model.ProfileImageNAme)" height="125" width="125" />
                                        }
                                        else
                                        {
                                            <img src="@(GlobalConfig.UserImageUrl+GlobalConfig.DefaultProfileImage)" height="200" width="200" />
                                        }
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-md-3"><b>Post Files:</b></label>
                                    <div class="col-md-1">:</div>

                                    @if (Model.PostFiles.Count > 0 && Model.PostFiles != null)
                                    {
                                        foreach (var i in Model.PostFiles)
                                        {
                                            if (i.IsVideo == true)
                                            {
                                                <div class="col-md-4">
                                                    @*<div class="carousel-item @(j == 0 ? "active" : "")">*@
                                                    <video width="600"  controls style="max-width:100%; height:200px;"> <source src="@(GlobalConfig.PostImageUrl + i.FileName)" type="video/mp4"> Your browser does not support HTML5 video.</video>
                                                    <br />
                                                </div>
                                                @*</div>*@
                                            }
                                            else
                                            {
                                                <div class="col-md-4">
                                                    @*<div class="carousel-item @(j == 0 ? "active" : "")">*@
                                                    <img width="100%" height="250px" class="d-block img-fluid" src="@(GlobalConfig.PostImageUrl + i.FileName)" alt="First slide">
                                                    <br />
                                                </div>
                                            }
                                            j++;
                                        }
                                    }

                                </div>
                                <br />

                                <div class="form-group row">
                                    <label class="col-md-4"><b>NickName</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @(Model.NickName)
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4"><b>Created date</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @(Model.CreatedDate.ToString("dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture))
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4"><b>Time Ago</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @(Model.Timeago)
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4"><b>Description</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @(Model.Description)
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4"><b>Hashtag</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @if (Model.HashTags != null)
                                        {
                                            <ul>
                                                @foreach (var tag in Model.HashTags)
                                                {
                                                    <li>@tag.hashtag</li>
                                                }
                                            </ul>
                                        }
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4"><b>Likes</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @Model.PostLikes
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4"><b>Comments</b></label>
                                    <div class="col-md-1">:</div>
                                    <div class="col-md-6">
                                        @(Model.Comments.Count())
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Stylaaa.Admin/Views/Post/ReportedPost.cshtml
@model IQueryable<ReportedPostList>
@using GridMvc.Html
@{
    ViewBag.Title = "ReportedPost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@helper LoadImage(string item)
{
    if (!String.IsNullOrWhiteSpace(item))
    {
            <img src="@(GlobalConfig.UserImageUrl + item )" alt="@item" height="100" width="100" />
    }
    else
    {
            <img src="@Url.Content("~/Files/DefaultImages/profile-placeholder.png")" alt="Default-Image" height="100" width="100" />
    }
}

@helper ActionButtons(long PostId)
{
    <a href="@Url.Action("DeleteRepoetedPost", "Post", new { @Id = PostId })" class="btn btn-sm btn-danger btnDelete" data-id="@PostId">
        <i class="icon-trash4"></i> Delete Post
    </a>

    <a href="@Url.Action("Postdetail", "Post", new { @Id = PostId })" class="btn btn-sm btn-primary btn-blue">
        <i class="icon-box"></i> View Post
    </a>
}

@helper LoadReviewBy(ReportedPostList item)
{
    <a href="@Url.Action("Detail", "User", new { @id = item.reportedbyUserId})">@item.reporedbyName</a>
}

@helper LoadPostBy(ReportedPostList item)
{
    <a href="@Url.Action("Detail", "User", new { @id = item.StylishId})">@item.Name</a>
}
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Reported Post </h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add()
                              .Titled("ReportBy")
                              .Sanitized(false).Encoded(false)
                              .RenderValueAs(x => LoadImage(x.ProfileImageNAme));

                               column.Add(p => p.reporedbyName)
                               .Titled("Report By")
                               .Sortable(true)
                               .Filterable(true)
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => LoadReviewBy(x));

                               column.Add(p => p.Name)
                               .Titled("Post By")
                               .Sortable(true)
                               .Filterable(true)
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => LoadPostBy(x));

                               column.Add(p => p.Reason)
                              .Titled("Reason")
                              .Sortable(true)
                              .Filterable(true);

                               column.Add(p => p.CreatedDate)
                             .Titled("Created Date")
                             .Sortable(true)
                             .Filterable(true)
                             .RenderValueAs(p => p.CreatedDate.ToString("dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture));

                               column.Add()
                               .Titled("Action")
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => ActionButtons(x.PostId));

                           }).Selectable(false).WithPaging(30)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.min.js")"></script>
    <script type="text/javascript">
        ActiveMenu("Report");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');
    </script>
}

Stylaaa.Admin/Views/Post/SpamComments.cshtml
@model IQueryable<SpamCommentsListModel>
@using GridMvc.Html
@{
    ViewBag.Title = "SpamComments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@helper LoadComentedByName(SpamCommentsListModel item)
{
    <a href="@Url.Action("Detail", "User", new { @id = item.CommentedById })">@item.CommentedByName</a>
}

@helper LoadPostByName(SpamCommentsListModel item)
{
    <a href="@Url.Action("Detail", "User", new { @id = item.CommentedById })">@item.PostByName</a>
}

@helper ActionButtons(long CommentID)
{
    <a href="@Url.Action("DeleteSpamComments", "Post", new { @Id = CommentID })" class="btn btn-sm btn-danger btnDelete" data-id="@CommentID">
        <i class="icon-trash4"></i> Delete
    </a>
}
<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Spam Comments </h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add()
                              .Titled("PostBy")
                              .Sanitized(false).Encoded(false)
                              .RenderValueAs(x => LoadPostByName(x));

                               column.Add()
                             .Titled("CommentBy")
                             .Sanitized(false).Encoded(false)
                             .RenderValueAs(x => LoadComentedByName(x));

                               column.Add(p => p.Commenttext)
                               .Titled("CommentText")
                               .Sortable(true)
                               .Filterable(true);

                               column.Add()
                              .Titled("Delete")
                              .Sanitized(false).Encoded(false)
                              .RenderValueAs(x => ActionButtons(x.CoomentId));

                           }).Selectable(false).WithPaging(30)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.min.js")"></script>
    <script type="text/javascript">
        ActiveMenu("SpamComments");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');
    </script>
}