Stylaaa.Web/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using Stylaaa.Core.Helper;
using Stylaaa.Core.Models;
using Stylaaa.Services;
using Stylaaa.Web.Filter;
using System.IO;
using System.Threading.Tasks;

namespace Stylaaa.Web.Controllers
{
    [CompleteProfileSetup(Role.Stylist, Role.User)]
    public class JobController : BaseController
    {
        private JobServices _service;
        private UserService _user;
        private CategoryService _catService;
        private GeneralServices _general;
        private StylishServices _stylist;

        public JobController()
        {
            _stylist = new StylishServices();
            _general = new GeneralServices();
            _catService = new CategoryService();
            _service = new JobServices();
            _user = new UserService();
        }

        public ActionResult AddJob()
        {
            string UserId = User.Identity.GetUserId();
            AddJobModel model = new AddJobModel() { JobCategoryList = _catService.GetJobCategoryList(_user.GetLanguage(UserId)) };
            return PartialView("_AddEditJob", model);
        }

        [HttpPost]
        public async Task<JsonResult> AddEditJob(AddJobModel model, FormCollection frm)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if (ModelState.IsValid)
            {
                //if(string.IsNullOrEmpty(model.HiddenJobFileName))
                //{
                //    model.HiddenJobFileName = "DefaultJob.jpg";
                //}
                if (!string.IsNullOrWhiteSpace(model.HiddenJobFileName))
                {
                    model.JobFilesNamesArray = model.HiddenJobFileName.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries).Select(x => x.ToString()).ToArray();
                }
                model.UserId = User.Identity.GetUserId();
                mResult = await _service.AddEditJob(model);
            }
            else
            {
                mResult.Message = "please fill the required data.";
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> EditJob(long id)
        {            
            AddJobModel model = new AddJobModel();
            string UserId = User.Identity.GetUserId();
            if (id > 0)
            {
                model = await _service.GetJobdetailEdit(_user.GetLanguage(UserId), id, UserId);
            }
            return PartialView("_AddEditJob", model);
        }

        [HttpPost]
        public JsonResult AddJobImage(FormCollection frm)
        {
            MediaResponseModel<object> mResult = new MediaResponseModel<object>();
            var userid = User.Identity.GetUserId();

            string pngimageData = frm["pngimageData"].ToString();
            string strFileName = frm["filename"].ToString();
            string strExistFileName = frm["existFileName"].ToString();
            string shortGuid = ShortGuid.NewGuid().ToString();
            if (!String.IsNullOrWhiteSpace(strExistFileName))
            {
                string strExistFilePath = GlobalConfig.JobImagePath + strExistFileName;
                if (System.IO.File.Exists(strExistFilePath))
                {
                    System.IO.File.Delete(strExistFilePath);
                }
            }
            strFileName = userid + "_" + shortGuid + "_" + DateTime.Now.ToString("ddMMyyyyhhmmss") + Path.GetExtension(strFileName);
            string strFilePath = Path.Combine(GlobalConfig.JobImagePath, strFileName);

            string img = pngimageData.Replace("data:image/png;base64,", "").Replace(' ', '+');
            //byte[] decodedData = Convert.FromBase64String(img);
            //System.IO.File.WriteAllBytes(strFilePath, decodedData);

            Utility.SaveCropImage(img, strFilePath, Path.GetExtension(strFileName));

            mResult.FileName = strFileName;
            mResult.MediaPath = GlobalConfig.JobImageUrl + strFileName;

            mResult.Result = ResponseStatus.Success;
            mResult.Message = "Success";

            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddJobMedia(IEnumerable<HttpPostedFileBase> uploadedFile)
        {
            MediaResponseModel<object> mResult = new MediaResponseModel<object>();
            string strFileName = "";
            var userid = User.Identity.GetUserId();

            try
            {
                foreach (HttpPostedFileBase fileMedia in uploadedFile)
                {
                    if (fileMedia != null && fileMedia.ContentLength > 0)
                    {
                        string shortGuid = ShortGuid.NewGuid().ToString();
                        strFileName = userid + "_" + shortGuid + "_" + DateTime.Now.ToString("ddMMyyyyhhmmss") + Path.GetExtension(fileMedia.FileName);

                        fileMedia.SaveAs(Path.Combine(GlobalConfig.JobImagePath, strFileName));

                        string[] mediaExtensions = { ".MP4", ".WMV" };
                        mResult.FileName += strFileName + ",";

                        if (IsMediaFile(mediaExtensions, strFileName))
                        {
                            mResult.MediaPath += GlobalConfig.JobImageUrl + strFileName + ",";
                        }
                        else
                        {
                            mResult.MediaPath += GlobalConfig.JobImageUrl + strFileName + ",";
                        }

                        mResult.Result = ResponseStatus.Success;
                        mResult.Message = "Success";
                    }
                    else
                    {
                        mResult.Result = ResponseStatus.Failed;
                        mResult.Message = "Failed";
                        mResult.Message = "please upload file";
                    }
                }
            }
            catch (Exception ex)
            {
                mResult.Result = ResponseStatus.Failed;
                mResult.Message = ex.Message;
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        public static bool IsMediaFile(string[] mediaExtensions, string path)
        {
            return -1 != Array.IndexOf(mediaExtensions, Path.GetExtension(path).ToUpperInvariant());
        }

        [HttpPost]
        public JsonResult DeleteMedia()
        {
            MediaResponseModel<object> mResult = new MediaResponseModel<object>();
            string strFileName = Request.Form["filename"].ToString();
            string FilePath = GlobalConfig.JobImagePath + strFileName;
            if (System.IO.File.Exists(FilePath))
            {
                System.IO.File.Delete(FilePath);
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> ViewAllJob()
        {
            string userid = User.Identity.GetUserId();
            List<ViewJobListModel> joblist = new List<ViewJobListModel>();
            jobFilterModel jobfilter = new jobFilterModel { UserId = userid, JobPageIndex = 1 };
            joblist = await _service.GetJobList(jobfilter);
            return PartialView("_JobList", joblist);
        }

        [HttpPost]
        public async Task<ActionResult> LoadMoreJob(jobFilterModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                string UserId = User.Identity.GetUserId();
                model.UserId = UserId;
                ViewBag.PageIndex = 1;
                List<ViewJobListModel> data = await _service.GetJobList(model);
                if (model.JobPageIndex == 1)
                    model.JobPageIndex = 2;
                return PartialView("_JobList", data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public async Task<JsonResult> DeleteJob(long id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            string UserId = User.Identity.GetUserId();
            if (id > 0)
            {
                mResult = await _service.DeleteJob(id);
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public async Task<ActionResult> PartialJob(int intPageIndex, string username)
        {
            string UserId = _user.GetUserID(username);
            GetUserJobs getJobListModel = new GetUserJobs();
            getJobListModel.RecentJobPageIndex = intPageIndex;
            getJobListModel = await _service.JoblistByUser(new PaginationModel { PageIndex = getJobListModel.RecentJobPageIndex, UserId = UserId });

            GetUserJobs totalrecentjob = await _service.JoblistByUser(new PaginationModel { PageIndex = 0, UserId = UserId });
            decimal totarecentjobCount = totalrecentjob.UserJobList.Count;

            getJobListModel.RecentJobPageCount = Math.Ceiling((decimal)(totarecentjobCount > 0 ? (totarecentjobCount / GlobalConfig.PageSize) : 0));

            return PartialView("_ProfileJob", getJobListModel);
        }

        public async Task<JsonResult> jobActiveToggle(long id)
        {
            ResponseModel<object> mResult = new ResponseModel<object>();
            if (id > 0)
            {
                mResult = await _service.JobActiveToggle(id);
                if(mResult.Status==ResponseStatus.Success)
                {
                    return Json(mResult, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                mResult.Status = ResponseStatus.Failed;
                mResult.Message = "please select jobId";
            }
            return Json(mResult, JsonRequestBehavior.AllowGet);
        }
    }
}

Stylaaa.Web/Views/Job/_AddEditJob.cshtml
@model AddJobModel
@{
                /**/

                /**/

                Layout = null;
}
<style>
    .pac-container {
        z-index: 100000 !important;
    }
</style>
<div class="popup-box">
    <div id="add-job" class="popup-max">
        <div class="" align="center">
            <a href="Javascript:;" title=""><img id="jobloader-post" class="rotate-loader" width="36" src="@Url.Content("~/Content/images/rectangle-2.svg")" style="display:none;" alt=""></a>
        </div>
        <input type="hidden" id="hdnDeleteJobMediaUrl" value="@Url.Action("DeleteMedia", "Job")" />
        @using (Ajax.BeginForm("AddEditJob", "Job",
                    new AjaxOptions
                    {
                        OnSuccess = "OnSuccessJob",
                        OnFailure = "OnFailure",
                        LoadingElementId = "progress",
                        OnBegin = "return FormJobValidation();"
                    }, new { id = "frm-add-job" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.LocationLatitude)
            @Html.HiddenFor(x => x.LocationLongitude)
            @Html.HiddenFor(x => x.Country)
            @Html.HiddenFor(x => x.HiddenJobFilePath)

            <div class="popup-had">
                @if (Model.Id > 0)
                {
                    <h4>Update Job</h4>
                }
                else
                {
                    <h4>@Resource.AddJobPopup</h4>
                }
                <a href="#" title="" class="cancel-pp" onclick="return confirmSaveJobData();"><img src="@Url.Content("~/Content/images/close.svg")" alt="" /></a>
            </div>
            <div class="popup-tabs">
                <ul>
                    <li><a href="#jobupload" title="@Resource.Upload" class="uploadsec">@Resource.Upload</a></li>
                    <li><a href="javascript:void(0)" title="@Resource.Crop" class="checkjobFileUpload">@Resource.Crop</a></li>
                    <li><a href="#jobdescription" title=@Resource.addPostDescription>@Resource.addPostDescription</a></li>
                </ul>
            </div>
            <div class="tabs-full-popup">
                <div id="jobupload">
                    <div class="popup-middle">
                        <div class="crop-box data-div-placeholder-content">
                            <div class="crop-image-section">
                                <div class="img-upload-max"></div>
                                <div><p>@Resource.editProProfileSizeValid</p></div>
                            </div>
                        </div>
                    </div>

                    <div class="upload-button">
                        <p style="color:black; padding-bottom: 10px;">@Resource.AddJobUploadDescription</p>
                    </div>
                    <div class="upload-button">
                        <a href="#" title=@Resource.Upload @Resource.Coverphoto class="btn-yellow">
                            + @Resource.AddJobAddImage
                            <input id="jobnewFile" name="jobnewFile" class="file-input" type="file" multiple onchange="fnUploadNewJobFile('@Url.Action("AddJobMedia", "job")')">
                        </a>
                    </div>

                    <div class="next-button">
                        @*<a href="#" title="Next" class="add-new-file checkjobFileUpload">Skip</a>*@
                        <a href="#" title="Next" class="add-new-file" id="skip">@Resource.skip</a>
                    </div>
                </div>
                <div id="jobcrop" style="display:none;">
                    <div class="crop-box">
                        <div class="pagination-image">
                            <div class="mrg-pg" id="job-crop-image-array">
                            </div>
                            @Html.HiddenFor(x => x.HiddenJobFileName, new { @class = "checkvalue" })
                        </div>
                        <div class="crop-image-section">
                            <canvas id="jobcanvas" class="img-upload-max "></canvas>
                            <div id="jobimage-container" class="addpost-image-container">
                                <img id="jobimage" src="" alt="Picture" class="cropper-hidden">
                            </div>
                            <div class="ps-upload hide">
                                <input type="hidden" id="jobexistFileName" name="existFileName" />
                                <input type="hidden" id="jobexistFileUrl" name="existFileUrl" />
                                <div class="bt-crop">
                                    <input type="button" id="btnLeftRotate" value="@Resource.Crop" title="rotate left" onclick="rotateLeft()" />
                                    <img id="btnCrop" src="@Url.Content("~/Content/images/rotate-left.svg")" title="rotate left" alt="rotate left" style="width: 40px;height: 40px;" />
                                </div>
                                <div class="bt-crop">
                                    <input type="button" id="btnRightRotate" value="@Resource.Crop" title="rotate right" onclick="rotateRight()" />
                                    <img id="btnCrop" src="@Url.Content("~/Content/images/rotate-right.svg")" title="rotate right" alt="rotate right" style="width: 40px;height: 40px;" />
                                </div>
                                <div class="bt-crop">
                                    <input type="button" id="btnCrop" value="@Resource.Crop" title="crop" onclick="fnCropFileforJob('@Url.Action("AddJobImage", "Job")')" />
                                    <img id="btnCrop" src="@Url.Content("~/Content/images/crop-right.svg")" alt="" />
                                </div>
                                <div class="bt-crop-rs">
                                    <input type="button" id="btnRestore" value="@Resource.Restore" title="reset" onclick="fnCropClear()" class="btnsave" />
                                    <img src="@Url.Content("~/Content/images/crop-cancel.svg")" alt="" />
                                </div>
                            </div>
                            <div class="upload-button hide">
                                <a href="#" title="Upload Photo/Video" class="btn-yellow">
                                    @Resource.UploadPhotoVideo
                                    <input class="fileInput" id="JobfileInput" type="file">
                                </a>
                            </div>

                            <div class="loading-label hide" style="padding-top:10px;">
                                <label class="btn-yellow">@Resource.UploadingFile..........</label>
                            </div>
                        </div>
                    </div>
                    <div class="next-button">
                        <a href="#" id="nextcrop" title=@Resource.Next class="btn-yellow">@Resource.Next</a>
                    </div>
                </div>
                <div id="jobdescription" style="display:none;">
                    <div class="popup-middle">
                        <div class="field-rs">
                            <label>@Resource.jobTitle</label>
                            @Html.TextBoxFor(x => x.Title, new { placeholder = Resource.JobTitlePlaceholder })
                        </div>

                        <div class="field-rs">
                            <label>@Resource.Budget</label>
                            @Html.TextBoxFor(x => x.Price, new { placeholder = Resource.BudgetPlaceholder, @onkeypress = "javascript:return EnsureDecimal(event)" })
                        </div>

                        <div class="field-rs">
                            <label>@Resource.AddJobZipcode</label>
                            @Html.TextBoxFor(x => x.ZipCode, new { @placeholder = Resource.zipcode, @class = "googleaddress", @autocomplete = "off" })
                        </div>

                        <div class="field-rs">
                            <label>@Resource.SelectService</label>
                            <div class="check-box">
                                @{
                                    if (Model != null && Model.JobCategoryList != null)
                                    {
                                        for (int i = 0; i < Model.JobCategoryList.Count; i++)
                                        {
                                            @Html.HiddenFor(x => Model.JobCategoryList[i].Id)
                                            <div class="chek-bx">
                                                @Html.CheckBoxFor(x => Model.JobCategoryList[i].Selected, new { id = "PostCategoryList_" + Model.JobCategoryList[i].Id + "___Id", name = Model.JobCategoryList[i].Id })
                                                @Html.LabelFor(x => Model.JobCategoryList[i].Id, Model.JobCategoryList[i].CategoryName, new { @for = "PostCategoryList_" + Model.JobCategoryList[i].Id + "___Id", @class = "check-label" })
                                            </div>
                                        }
                                    }
                                }
                            </div>
                        </div>
                    </div>
                    <div class="popup-footer">
                        <input type="submit" class="button share-button" value="@Resource.AddJobSubmitBtn" />
                        <a href="#" title="Cancel" class="button" style="margin-left: 0;" onclick="return confirmSaveJobData();">@Resource.forgotpasswordCancel</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Stylaaa.Web/Views/Job/_JobList.cshtml
@model List<ViewJobListModel>
@if (Model != null && Model.Any())
{
    foreach (var job in Model)
    {
        <div class="profile-box">
            <div class="profile-bx" style="border: 1px solid #f2f2f2; border-spacing: 3px; border-radius: 5px;">
                <div class="front-bx">
                    <div class="product-img">
                        @if (job.JobFilesList.Count() > 0)
                        {
                            <img style="max-height: 295px; min-height: 295px;" class="pd-img" src="@(GlobalConfig.JobImageUrl + (job.JobFilesList.FirstOrDefault().FileName != null ? job.JobFilesList.FirstOrDefault().FileName : "DefaultJob.jpg"))" alt="" />
                        }
                        else
                        {
                            <img style="max-height: 295px;" class="pd-img" src="@(GlobalConfig.JobImageUrl + "DefaultJob.jpg")" alt="" />
                        }
                    </div>
                    <div class="profile-content">
                        <h5>@job.Title</h5>
                        <h6>@job.Price €</h6>
                    </div>
                    <div class="location-job">
                        <span class="location-icon">@job.Country, @job.Zipcode</span>
                    </div>
                    <div class="profile-btn job-tags">
                        <div class="table">
                            <div class="table-cell">
                                @if (job.JobCategoryList != null)
                                {
                                    foreach (var category in job.JobCategoryList)
                                    {
                                        <a href="#">@category.CategoryName</a>
                                    }
                                }

                            </div>
                            @if (ViewBag.MyRole == Role.Stylist)
                            {
                                <div class="table-cell">
                                    @if (Convert.ToInt32(ViewBag.Credit) > 0)
                                    {
                                        <a href="javascript:;" title="" class="pf-chet"></a>
                                    }
                                    else
                                    {
                                        <a href="#purchas-popup" title="" class="pf-chet"></a>
                                    }
                                </div>
                            }
                        </div>
                    </div>
                </div>
                <div class="profile-ps-box">
                    <a href="javascript:;" title="" class="close-profile-message"><img src="@Url.Content("~/Content/images/close.svg")" alt="" /></a>

                    <div class="profile-field">
                        <label>@Resource.message</label>
                        <textarea placeholder="@Resource.typehere"></textarea>
                    </div>
                    @if (job.IsAbleToSend)
                    {
                        <a href="javascript:;" title="Send" data-id="@job.UserId" data-jid="@job.JobId" class="btn-follow sendjobmesssage">@Resource.send</a>
                    }
                    else
                    {
                        if (Convert.ToInt32(ViewBag.Credit) > 0)
                        {
                            <a href="javascript:;" title="Send" data-id="@job.UserId" data-jid="@job.JobId" class="btn-follow sendcredit">@Resource.send</a>
                        }
                        else
                        {
                            <a href="#purchas-popup" title="Send" data-id="@job.UserId" data-jid="@job.JobId" class="btn-follow fancybox">@Resource.send</a>
                        }
                    }
                </div>
            </div>
        </div>
    }

}

Stylaaa.Web/Views/Job/_ProfileJob.cshtml
@model GetUserJobs

@if (Model.UserJobList != null)
{

    for (int i = 0; i < Model.UserJobList.Count; i++)
    {
        string notactivediv = "";
        if (Model.UserJobList[i].Status == JobStatus.Deactivate)
        {
            notactivediv = "nt-active-div";
        }
        else if (Model.UserJobList[i].Status == JobStatus.Completed)
        {
            notactivediv = "nt-active-div";
        }
        else
        {
            notactivediv = "";
        }

        <div class="job-bx @notactivediv">
            <div class="product-img">
                @if (Model.UserJobList[i].JobFilesList.Count() > 0)
                {
                    <img class="pd-img" style="max-height: 295px;" src="@(GlobalConfig.JobImageUrl+Model.UserJobList[i].JobFilesList.FirstOrDefault().FileName)" alt="" />
                }
                else
                {
                    <img class="pd-img" style="max-height: 295px;" src="@(GlobalConfig.JobImageUrl + "DefaultJob.jpg")" alt="" />
                }
                
                @if (Model.UserJobList[i].Status == JobStatus.Deactivate)
                {
                    <a href="#" class="job-status job-not-active">@Resource.jobNotActive</a>
                }
                else if (Model.UserJobList[i].Status == JobStatus.Completed)
                {
                    <a href="#" class="job-status job-completed">@Resource.JobCompleted</a>
                }
                else
                {

                }
            </div>
            <div class="profile-content">
                <h5>@Model.UserJobList[i].Title</h5>
                <h6>@Model.UserJobList[i].Price €</h6>
            </div>
            <div class="location-job">
                <span class="location-icon">@Model.UserJobList[i].Country, @Model.UserJobList[i].Zipcode</span>
            </div>
            <div class="profile-btn job-tags">
                <div class="table">
                    <div class="table-cell">
                        @foreach (var job in Model.UserJobList[i].JobCategoryList)
                        {
                            <a href="javascript:;">@job.CategoryName</a>
                        }
                    </div>
                    <div class="table-cell">
                        <div class="product-new-ctn">
                            <div class="product-lk">
                                <div class="more-link">
                                    <img src="~/Content/images/more.svg" alt="" />
                                    <ul class="more-link-bx">
                                        <li><a href="javascript:;" title="Edit" onclick="editJob('@Url.Action("EditJob", "Job", new { id = Model.UserJobList[i].JobId })')">@Resource.edit</a></li>
                                        @if (Model.UserJobList[i].Status == JobStatus.Activated)
                                        {
                                            <li><a href="javascript:;" title="Deactivate" onclick="ActiveTogglejs('@Url.Action("jobActiveToggle", "Job", new { id = Model.UserJobList[i].JobId })')">@Resource.deactivate</a></li>
                                        }
                                        else
                                        {
                                            <li><a href="javascript:;" title="Deactivate" onclick="ActiveTogglejs('@Url.Action("jobActiveToggle", "Job", new { id = Model.UserJobList[i].JobId })')">@Resource.Activate</a></li>
                                        }

                                        <li><a href="javascript:;" title="Delete" onclick="deleteProfileJob('@Url.Action("DeleteJob", "Job", new { id = Model.UserJobList[i].JobId })')">@Resource.delete</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}