Stylaaa.Admin/Controllers/CategoryController.cs
using Microsoft.AspNet.Identity;
using Stylaaa.Admin.Filter;
using Stylaaa.Core.Helper;
using Stylaaa.Core.Models;
using Stylaaa.Services;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stylaaa.Admin.Controllers
{
    [CustomAuthorization]
    public class CategoryController : BaseController
    {
        private CategoryService _catService;
        private UserService _user;

        ResponseModel<object> mResult;

        public CategoryController()
        {
            _catService = new CategoryService();
            _user = new UserService();
        }
        public ActionResult Index()
        {
            string UserId = User.Identity.GetUserId();
            IQueryable<CategoryModel> Categorieslist = _catService.IQueryable_CategoryList(_user.GetLanguage(UserId));
            return View(Categorieslist);
        }

        public async Task<ActionResult> Add()
        {
            AdminCategoryModel model = new AdminCategoryModel();
            List<CategoryLanguageModel> CategoryLanguages = new List<CategoryLanguageModel>();
            CategoryLanguages.Add(new CategoryLanguageModel()
            {
                LanguageId = languageType.English,
                LanguageName = languageType.English.ToString(),
            });

            CategoryLanguages.Add(new CategoryLanguageModel()
            {
                LanguageId = languageType.German,
                LanguageName = languageType.German.ToString(),
            });

            model.CategoryLanguageModelList = CategoryLanguages;
            return View("ManageCategory", model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(AdminCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                bool isDuplicate = _catService.isCategoryDuplicate(model);
                if (isDuplicate)
                {
                    OnBindMessage(AlertStatus.danger, "Duplicate Category Name");
                    ModelState.AddModelError("", "Duplicate Category Name");
                }
                else
                {
                    if (model.fileBaseImage != null)
                    {
                        //Stream inStream = model.fileBaseImage.InputStream;
                        //Image PostedImage = Image.FromStream(inStream);

                        string ogFileName = model.fileBaseImage.FileName.Trim('\"');
                        string shortGuid = ShortGuid.NewGuid().ToString();
                        var thisFileName = shortGuid + Path.GetExtension(ogFileName);
                        model.fileBaseImage.SaveAs(Path.Combine(GlobalConfig.CategoryImagePath, thisFileName));
                        model.ImageName = thisFileName;
                    }
                    mResult = await _catService.InsertOrUpdateCategory(model);
                    OnBindMessage(mResult.Status, mResult.Message);

                    if (mResult.Status == ResponseStatus.Success)
                        return RedirectToActionPermanent("Index");
                }
            }
            return View("ManageCategory", model);
        }

        public async Task<ActionResult> Edit(long id)
        {
            AdminCategoryModel model = await _catService.GetCategoryDetail(id);
            if (model == null)
                return RedirectToActionPermanent("Index");
            return View("ManageCategory", model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AdminCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                bool isDuplicate = _catService.isCategoryDuplicate(model);
                if (isDuplicate)
                {
                    OnBindMessage(AlertStatus.danger, "Duplicate Category Name");
                    ModelState.AddModelError("", "Duplicate Category Name");
                }
                else
                {
                    if (model.fileBaseImage != null)
                    {
                        //Stream inStream = model.fileBaseImage.InputStream;
                        //Image PostedImage = Image.FromStream(inStream);

                        string ogFileName = model.fileBaseImage.FileName.Trim('\"');
                        string shortGuid = ShortGuid.NewGuid().ToString();
                        var thisFileName = shortGuid + Path.GetExtension(ogFileName);

                        model.fileBaseImage.SaveAs(Path.Combine(GlobalConfig.CategoryImagePath, thisFileName));
                        //}
                        model.ImageName = thisFileName;
                    }

                    mResult = await _catService.InsertOrUpdateCategory(model);
                    OnBindMessage(mResult.Status, mResult.Message);

                    if (mResult.Status == ResponseStatus.Success)
                        return RedirectToActionPermanent("Index");
                }
            }
            return View("ManageCategory", model);
        }
        

        public async Task<ActionResult> DeleteCategory(long Id)
        {
            mResult = await _catService.DeleteCategory(Id);
            OnBindMessage(mResult.Status, mResult.Message);
            return RedirectToActionPermanent("Index");
        }
    }
}

Stylaaa.Admin/Controllers/CountryController.cs
using Stylaaa.Admin.Filter;
using Stylaaa.Core.Helper;
using Stylaaa.Core.Models;
using Stylaaa.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stylaaa.Admin.Controllers
{
    [CustomAuthorization]
    public class CountryController : BaseController
    {
        private CountryServices _country;
        public CountryController()
        {
            _country = new CountryServices();
        }

        public ActionResult Index()
        {
            IQueryable<CountryModel> Categorieslist = _country.IQueryable_Country();
            return View(Categorieslist);
        }

        public ActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("ManageCountry");
        }

        [HttpPost]
        public async Task<ActionResult> Add(CountryModel cmodel)
        {
            if (ModelState.IsValid)
            {
                bool IsDuplicate = _country.IsDuplicateCountry(cmodel);
                if (IsDuplicate)
                {
                    string Error = "Another Country is Already  Exist with Same Name";
                    TempData["alertModel"] = new AlertModel(AlertStatus.danger, Error);
                    ModelState.AddModelError("", Error);
                }
                else
                {
                    long id = await _country.InsertOrUpdateCountry(cmodel);
                    if (id > 0)
                    {
                        TempData["alertModel"] = new AlertModel(AlertStatus.success, "Country added successfully !");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        string Msg = "Failed to add Country!";
                        TempData["alertModel"] = new AlertModel(AlertStatus.danger, Msg);
                        ModelState.AddModelError("", Msg);
                    }
                }
            }
            return View("ManageCountry", cmodel);
        }

        public async Task<ActionResult> Edit(long Id)
        {
            CountryModel objCountry = await _country.EditCountryById(Id);
            if (objCountry == null)
                return RedirectToActionPermanent("Index");
            ViewBag.Action = "Edit";
            return View("ManageCountry", objCountry);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CountryModel model)
        {
            if (ModelState.IsValid)
            {
                bool IsDuplicate = _country.IsDuplicateCountry(model);
                if (IsDuplicate)
                {
                    string Error = "Another Country is Already  Exist with Same Name";
                    TempData["alertModel"] = new AlertModel(AlertStatus.danger, Error);
                    ModelState.AddModelError("", Error);
                }
                else
                {
                    long id = await _country.InsertOrUpdateCountry(model);
                    if (id > 0)
                    {
                        TempData["alertModel"] = new AlertModel(AlertStatus.success, "Country Edited successfully !");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        string Msg = "Failed to Edit Country!";
                        TempData["alertModel"] = new AlertModel(AlertStatus.danger, Msg);
                        ModelState.AddModelError("", Msg);
                    }
                }
            }
            return View("ManageCountry", model);
        }

        public async Task<ActionResult> Delete(long Id)
        {
            ResponseModel<object> mResult = await _country.DeleteCountry(Id);
            TempData["alertModel"] = new AlertModel(mResult.Status == ResponseStatus.Success ? AlertStatus.success : AlertStatus.danger, mResult.Message);
            return RedirectToAction("Index");
        }
    }
}

Stylaaa.Admin/Views/Country/Index.cshtml
@model IQueryable<CountryModel>
@using GridMvc.Html
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/css/gridMvc")

@using (Html.BeginForm("Delete", "Category", FormMethod.Post, new { @class = "form-horizontal form-simple", @id = "frmDelete" }))
{
    @Html.Hidden("Id")
}

@helper ActionButtons(long Id)
{
    <div class="form-group row">
        <a href="@Url.Action("Edit", "Country",new { @Id=Id })" class="btn btn-sm btn-primary btn-blue">
            <i class="icon-edit2"></i> Edit
        </a>
        <a href="javascript:;" class="btn btn-sm btn-danger btnDelete" data-id="@Id">
            <i class="icon-trash4"></i> Delete
        </a>
    </div>

}

<section id="basic">
    <div class="row">
        <div class="col-xs-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Countries </h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li>
                                <a href="@Url.Action("Add","Country")">
                                    <i class="icon-plus3"></i>  Add New Country
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block card-dashboard">
                        <div id="basicScenario" class="jsgrid" style="position: relative;height: auto;width: 100%;">
                            <div class="jsgrid-grid-body">
                                @Html.Grid(Model).Columns(column =>
                           {
                               column.Add(p => p.Name)
                               .Titled("Category Name")
                               .Sortable(true)
                               .Filterable(true);

                               column.Add()
                               .Titled("Action")
                               .Sanitized(false).Encoded(false)
                               .RenderValueAs(x => ActionButtons(x.CountryId));

                           }).Selectable(false).WithPaging(30)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/gridMvc")
    <script src="@Url.Content("~/Content/Plugins/SweetAlert/sweetalert.min.js")"></script>
    <script type="text/javascript">
        ActiveMenu("Countries");
        $(".jsgrid-grid-body").css('overflow-x', 'auto');

        $('.btnDelete').on('click', function () {
            $('#frmDelete #Id').val($(this).data('id'));
            swal({
                title: "Are you sure?",
                //text: "You will not be able to recover this Category and related data",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DA4453",
                confirmButtonText: "Yes, delete it!",
                cancelButtonText: "No, cancel.",
                closeOnConfirm: false,
                closeOnCancel: false
            }, function (isConfirm) {
                if (isConfirm) {
                    swal("Delete!", "Selected Category will be deleted, and will not be rollback!!", "success");
                    $('#frmDelete').submit();
                    return true;
                } else {
                    swal("Cancelled", "It's safe.", "error");
                }
            });
        });
    </script>
}

Stylaaa.Admin/Views/Country/ManageCountry.cshtml
@model CountryModel
@{
    string Action = ViewBag.Action;
    ViewBag.Title = "ManageCountry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="validation">
    <div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm(Action, "Country", FormMethod.Post, new { @id = "frmAddEdit" }))
            {
                if (Model != null && Model.CountryId > 0)
                {
                    @Html.HiddenFor(x => x.CountryId)
                }

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">@Action Country</h4>
                        <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    </div>
                    <div class="card-body collapse in">
                        <div class="card-block">
                            @Html.ValidationSummary(true)
                            <div class="form-group row">
                                <div class="col-md-6">
                                    <div class="form-group row">
                                        <label class="col-md-5"> Enter Country Name <span class="red">*</span> <span class="icon-question-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="Please enter category name"></span></label>
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control required" })
                                            @Html.ValidationMessageFor(x => x.Name)
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-md-12">
                                            <input type="submit" class="btn btn-md btn-primary" value="Save" />
                                            <a href="@Url.Action("Index")" class="btn btn-md btn-grey">
                                                Cancel
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/jQuery/validate")
    <script src="@Url.Content("~/Content/Jquery/GeneralScript.js")"></script>
    <script type="text/javascript">
        ActiveMenu('Country')
    </script>
}